import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="bg-slate-800 border-b border-slate-700 text-white">
          <div className="max-w-7xl mx-auto flex items-center gap-8 p-4">
            <Link href="/">Home</Link>
            <Link href="/standings">Standings</Link>
            <Link href="/teams">Teams</Link>
            <Link href="/power-rankings">Power Rankings</Link>
            <Link href="/history">History</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );

}
